import type { Metadata } from 'next'
import './globals.css'
import { SidebarProvider } from '@/components/ui/sidebar'
import { AppSidebar } from '@/components/layout/app-sidebar'
import Navbar from '@/components/ui/navbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' data-theme='white'>
      <body
        className={`antialiased bg-white dark:bg-[#171717] dark:text-white`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main>
            <Navbar />

            <div className='sm:px-4 md:px-6 mt-6'>{children}</div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  )
}
